# Generated by Django 4.2.3 on 2023-08-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='valor_planejamento',
            field=models.FloatField(default=0),
        ),
    ]
